module Aws
  aws_components = %(./aws)
  Dir[%(#{aws_components}/*)].each do |component|
    load component
    method_name = File.basename(component, '.rb').to_sym
    define_singleton_method(method_name, method(method_name))
  end

  # use some implicit knowledge to generate AutomaticComponents
  # in order to standardize the Aws.component calling interface
  AUTOMATIC_COMPONENTS = %i[
    instance
    vpc
    subnet
    security_group
    lambda_function
    s3_bucket
    dynamodb_table
    elastic_beanstalk_environment
    iam_role
    rds_cluster
    ebs_volume
    autoscaling_group
    cloudwatch_metric_alarm
    ec2_transit_gateway
    ec2_transit_gateway_route_table
    ecs_cluster
    ecs_service
    eks_cluster
    elasticache_cluster
    elasticache_replication_group
    elb
    alb
    emr_cluster
    glacier_vault
    glue_catalog_database
    glue_catalog_table
    kinesis_firehose_delivery_stream
    kinesis_stream
    launch_template
    lb
    lb_listener
    lb_target_group
    nat_gateway
    network_acl
    route_table
    security_group_rule
    sns_topic
    sqs_queue
    vpn_connection
    vpn_gateway
    redshift_cluster
    cloudfront_distribution
    appmesh_mesh
    codebuild_project
    codecommit_repository
    codedeploy_app
    codedeploy_deployment_group
    codepipeline
    apigatewayv2_api
    apigatewayv2_domain_name
    batch_compute_environment
    batch_job_definition
    batch_job_queue
    cloud9_environment_ec2
    cloudtrail
    cloudwatch_event_permission
    cloudwatch_event_rule
    cloudwatch_event_target
    cloudwatch_log_group
    cloudwatch_log_metric_filter
    cloudwatch_log_resource_policy
    cloudwatch_log_stream
    cloudwatch_log_subscription_filter
    cloudwatch_metric_alarm
    config_aggregate_authorization
    config_config_rule
    config_configuration_recorder
    config_configuration_recorder_status
    config_delivery_channel
    config_organization_custom_rule
    config_organization_managed_rule
    dax_cluster
    dax_parameter_group
    dax_subnet_group
    devicefarm_project
    directory_service_conditional_forwarder
    directory_service_directory
    directory_service_log_subscription
    dms_certificate
    dms_endpoint
    dms_replication_instance
    dms_replication_subnet_group
    dms_replication_task
    docdb_cluster
    docdb_cluster_instance
    docdb_cluster_parameter_group
    docdb_cluster_snapshot
    docdb_subnet_group
    dx_bgp_peer
    dx_connection
    dx_connection_association
    dx_gateway
    dx_gateway_association
    dx_gateway_association_proposal
    dx_hosted_private_virtual_interface
    dx_hosted_private_virtual_interface_accepter
    dx_hosted_public_virtual_interface
    dx_hosted_public_virtual_interface_accepter
    dx_lag
    dx_private_virtual_interface
    dx_public_virtual_interface
    dx_transit_virtual_interface
    ebs_default_kms_key
    ebs_encryption_by_default
    ebs_snapshot
    ebs_snapshot_copy
    ebs_volume
    ec2_availability_zone_group
    ec2_capacity_reservation
    ec2_carrier_gateway
    ec2_client_vpn_authorization_rule
    ec2_client_vpn_endpoint
    ec2_client_vpn_network_association
    ec2_client_vpn_route
    ec2_fleet
    ec2_local_gateway_route
    ec2_local_gateway_route_table_vpc_association
    ec2_managed_prefix_list
    ec2_tag
    ec2_traffic_mirror_filter
    ec2_traffic_mirror_filter_rule
    ec2_traffic_mirror_session
    ec2_traffic_mirror_target
    ec2_transit_gateway_peering_attachment
    ec2_transit_gateway_peering_attachment_accepter
    ec2_transit_gateway_prefix_list_reference
    ec2_transit_gateway_route
    ec2_transit_gateway_vpc_attachment
    ec2_transit_gateway_vpc_attachment_accepter
    ecr_lifecycle_policy
    ecr_registry_policy
    ecr_replication_configuration
    ecs_capacity_provider
    ecs_cluster
    ecs_service
    ecs_tag
    ecs_task_definition
    efs_access_point
    efs_file_system
    efs_mount_target
    eip
    eip_association
    eks_addon
    eks_cluster
    eks_fargate_profile
    eks_node_group
    elastic_beanstalk_application
    elastic_beanstalk_application_version
    elastic_beanstalk_configuration_template
    elastic_beanstalk_environment
    elasticache_cluster
    elasticache_parameter_group
    elasticache_replication_group
    elasticache_security_group
    elasticache_subnet_group
    elasticsearch_domain
    elasticsearch_domain_policy
    elb
    elb_attachment
    emr_cluster
    emr_instance_fleet
    emr_instance_group
    emr_managed_scaling_policy
    emr_security_configuration
    fsx_lustre_file_system
    fsx_windows_file_system
    gamelift_alias
    gamelift_build
    gamelift_fleet
    gamelift_game_session_queue
    gamelift_matchmaking_configuration
    gamelift_matchmaking_rule_set
    gamelift_script
    glacier_vault
    glacier_vault_lock
    glue_catalog_database
    glue_catalog_table
    glue_classifier
    glue_connection
    glue_crawler
    glue_data_catalog_encryption_settings
    glue_dev_endpoint
    glue_job
    glue_ml_transform
    glue_partition
    glue_registry
    glue_schema
    glue_security_configuration
    glue_trigger
    glue_user_defined_function
    glue_workflow
    guardduty_detector
    guardduty_invite_accepter
    guardduty_ipset
    guardduty_member
    guardduty_organization_admin_account
    guardduty_organization_configuration
    guardduty_publishing_destination
    guardduty_threatintelset
    iam_access_key
    iam_account_alias
    iam_account_password_policy
    iam_group
    iam_group_membership
    iam_group_policy
    iam_group_policy_attachment
    iam_instance_profile
    iam_openid_connect_provider
    iam_policy
    iam_policy_attachment
    iam_role
    iam_role_policy
    iam_role_policy_attachment
    iam_saml_provider
    iam_server_certificate
    iam_service_linked_role
    iam_user
    iam_user_group_membership
    iam_user_login_profile
    iam_user_policy
    iam_user_policy_attachment
    iam_user_ssh_key
    imagebuilder_component
    imagebuilder_distribution_configuration
    imagebuilder_image
    imagebuilder_image_pipeline
    imagebuilder_image_recipe
    imagebuilder_infrastructure_configuration
    inspector_assessment_target
    inspector_assessment_template
    inspector_resource_group
    iot_certificate
    iot_policy
    iot_policy_attachment
    iot_role_alias
    iot_thing
    iot_thing_principal_attachment
    iot_thing_type
    iot_topic_rule
    key_pair
    kinesis_analytics_application
    kinesis_analytics_v2_application
    kinesis_firehose_delivery_stream
    kinesis_stream
    kinesis_stream_consumer
    kinesis_video_stream
    kms_alias
    kms_ciphertext
    kms_external_key
    kms_grant
    kms_key
    lambda_alias
    lambda_code_signing_config
    lambda_event_source_mapping
    lambda_function
    lambda_function_event_invoke_config
    lambda_layer_version
    lambda_permission
    lambda_provisioned_concurrency_config
    launch_configuration
    launch_template
    lb_cookie_stickiness_policy
    lb_listener
    lb_listener_certificate
    lb_listener_rule
    lb_load_balancer_backend_server_policy
    lb_ssl_negotiation_policy
    lb_target_group
    lb_target_group_attachment
    licensemanager_association
    licensemanager_license_configuration
    lightsail_domain
    lightsail_instance
    lightsail_key_pair
    lightsail_static_ip
    lightsail_static_ip_attachment
    macie2_account
    macie2_classification_job
    macie2_custom_data_identifier
    macie2_findings_filter
    macie2_invitation_accepter
    macie2_member
    macie_member_account_association
    macie_s3_bucket_association
    main_route_table_association
    media_connect_flow
    media_package_channel
    media_store_container
    media_store_container_policy
    mq_broker
    mq_configuration
    mq_user
    mwaa_environment
    nat_gateway
    neptune_cluster
    neptune_cluster_instance
    neptune_cluster_parameter_group
    neptune_cluster_snapshot
    neptune_event_subscription
    neptune_parameter_group
    neptune_subnet_group
    network_acl
    network_acl_rule
    network_interface
    network_interface_attachment
    networkfirewall_firewall
    networkfirewall_firewall_policy
    networkfirewall_logging_configuration
    networkfirewall_resource_policy
    networkfirewall_rule_group
    opsworks_application
    opsworks_custom_layer
    opsworks_ganglia_layer
    opsworks_haproxy_layer
    opsworks_instance
    opsworks_java_app_layer
    opsworks_memcached_layer
    opsworks_mysql_layer
    opsworks_nodejs_app_layer
    opsworks_permission
    opsworks_php_app_layer
    opsworks_rails_app_layer
    opsworks_rds_db_instance
    opsworks_stack
    opsworks_static_web_layer
    opsworks_user_profile
    organizations_account
    organizations_delegated_administrator
    organizations_organization
    organizations_organizational_unit
    organizations_policy
    organizations_policy_attachment
    outposts_outpost
    outposts_outpost_instance_type
    outposts_site
    pinpoint_adm_channel
    pinpoint_apns_channel
    pinpoint_apns_sandbox_channel
    pinpoint_apns_voip_channel
    pinpoint_apns_voip_sandbox_channel
    pinpoint_app
    pinpoint_baidu_channel
    pinpoint_email_channel
    pinpoint_event_stream
    pinpoint_gcm_channel
    pinpoint_sms_channel
    placement_group
    proxy_protocol_policy
    qldb_ledger
    quicksight_group
    quicksight_group_membership
    quicksight_user
    ram_principal_association
    ram_resource_association
    ram_resource_share
    ram_resource_share_accepter
    rds_cluster
    rds_cluster_endpoint
    rds_cluster_instance
    rds_cluster_parameter_group
    rds_global_cluster
    redshift_cluster
    redshift_event_subscription
    redshift_ordered_snapshot
    redshift_parameter_group
    redshift_security_group
    redshift_snapshot_copy_grant
    redshift_snapshot_schedule
    redshift_snapshot_schedule_association
    redshift_subnet_group
    resourcegroups_group
    route
    route53_delegation_set
    route53_health_check
    route53_key_signing_key
    route53_query_log
    route53_record
    route53_resolver_dnssec_config
    route53_resolver_endpoint
    route53_resolver_firewall_domain_list
    route53_resolver_firewall_rule
    route53_resolver_firewall_rule_group
    route53_resolver_firewall_rule_group_association
    route53_resolver_forward_rule
    route53_resolver_query_log_config
    route53_resolver_query_log_config_association
    route53_resolver_rule
    route53_resolver_rule_action
    route53_resolver_rule_association
    route53_vpc_association_authorization
    route53_zone
    route53_zone_association
    route_table
    route_table_association
    s3_access_point
    s3_account_public_access_block
    s3_bucket
    s3_bucket_analytics_configuration
    s3_bucket_inventory_configuration
    s3_bucket_metric
    s3_bucket_notification
    s3_bucket_object
    s3_bucket_ownership_controls
    s3_bucket_policy
    s3_bucket_public_access_block
    s3control_bucket
    s3control_bucket_lifecycle_configuration
    s3control_bucket_policy
    s3outposts_endpoint
    sagemaker_app
    sagemaker_app_image_config
    sagemaker_autoscaling_policy
    sagemaker_code_repository
    sagemaker_device_fleet
    sagemaker_domain
    sagemaker_edge_packaging_job
    sagemaker_endpoint
    sagemaker_endpoint_configuration
    sagemaker_feature_group
    sagemaker_human_task_ui
    sagemaker_image
    sagemaker_image_version
    sagemaker_model
    sagemaker_model_package_group
    sagemaker_notebook_instance
    sagemaker_notebook_instance_lifecycle_configuration
    sagemaker_pipeline
    sagemaker_project
    sagemaker_user_profile
    sagemaker_workforce
    sagemaker_workteam
    secretsmanager_secret
    secretsmanager_secret_policy
    secretsmanager_secret_rotation
    secretsmanager_secret_version
    security_group
    security_group_rule
    securityhub_account
    securityhub_action_target
    securityhub_insight
    securityhub_invite_accepter
    securityhub_member
    securityhub_organization_admin_account
    securityhub_organization_configuration
    securityhub_product_subscription
    securityhub_standards_control
    securityhub_standards_subscription
    serverlessapplicationrepository_cloudformation_stack
    service_discovery_http_namespace
    service_discovery_private_dns_namespace
    service_discovery_public_dns_namespace
    service_discovery_service
    servicecatalog_budget_resource_association
    servicecatalog_constraint
    servicecatalog_group_configuration
    servicecatalog_organization_conformance_pack
    servicecatalog_portfolio
    servicecatalog_portfolio_share
    servicecatalog_principal_portfolio_association
    servicecatalog_product
    servicecatalog_provisioned_product
    servicecatalog_provisioning_artifact
    servicecatalog_service_action
    servicecatalog_tag_option
    servicecatalog_tag_option_resource_association
    servicequotas_service_quota
    servicequotas_service_quota_default
    ses_active_receipt_rule_set
    ses_configuration_set
    ses_domain_dkim
    ses_domain_identity
    ses_domain_identity_verification
    ses_domain_mail_from
    ses_email_identity
    ses_event_destination
    ses_identity_notification_topic
    ses_identity_policy
    ses_receipt_filter
    ses_receipt_rule
    ses_receipt_rule_set
    ses_template
    sfn_activity
    sfn_state_machine
    shield_protection
    shield_protection_group
    signer_signing_job
    signer_signing_profile
    signer_signing_profile_permission
    simpledb_domain
    snapshot_create_volume_permission
    sns_platform_application
    sns_sms_preferences
    sns_topic
    sns_topic_policy
    sns_topic_subscription
    spot_datafeed_subscription
    spot_fleet_request
    spot_instance_request
    sqs_queue
    sqs_queue_policy
    ssm_activation
    ssm_association
  ].freeze

  AUTOMATIC_COMPONENTS.each do |**kwargs|
    define_singleton_method(method_name) do
      component(resource: %(aws_${method_name}), **kwargs)
    end
  end
end
